(define (problem blockProblem)
    (:domain blockWorld)
    (:objects A B C D - block)
    (:init  (clear B)
            (on B A)
            (on A table)
            (clear C)
            (on C D)
            (on D table))
    (:goal (and (on A B) (on B C) (on C D) (on D table) (clear A)))
)