(define (problem blockProblem3)
    (:domain blockWorld)
    (:objects A B C D E F - block)
    (:init  (clear A)
            (on A B)
            (on B C)
            (on C D)
            (on D E)
            (on E F)
            (ontable F)
            (handempty))
    (:goal (and (on C E) (on E A) (on A F) (on F B) (on B D) (clear C) (ontable D) (handempty)))
)