(define (problem blockProblem2)
    (:domain blockWorld)
    (:objects A B C D E F - block)
    (:init  (clear A)
            (on A C)
            (on C E)
            (ontable E)
            (clear B)
            (on B D)
            (on D F)
            (ontable F)
            (handempty))
    (:goal (and (on A B) (on B C) (on C D) (on D E) (on E F) (clear A) (ontable F) (handempty)))
)