(define (problem blockProblem1)
    (:domain blockWorld)
    (:objects A B C D - block)
    (:init  (clear B)
            (ontable A)
            (on B A)
            (clear C)
            (ontable D)
            (on C D)
            (handempty))
    (:goal (and (on A B) (on D C) (clear A) (clear D) (ontable B) (ontable C) (handempty)))
)